[tool.poetry]
name = "try-monorepo"
version = "0.1.0"
description = ""
authors = ["Anca Chereches <anca.c@transitionzero.org>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
myapp = {path = "apps/myapp", develop = true}
tz-api-utils = {path = "libraries/api-utils", develop = true}
tz-processing-utils = {path = "libraries/processing-utils", develop = true}

[tool.poetry.group.dev.dependencies]
pytest = "^8.3.3"
black = "^24.10.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.black]
line-length = 120
include = '\.pyi?$'
exclude = '''
    /(
        \.ipynb_checkpoints  # Exclude Jupyter notebook checkpoints
        | \.venv             # Exclude virtual environments
        | .*\.ipynb          # Exclude Jupyter notebooks
    )/
'''
target-version = ['py311']