[tool.poetry]
name = "tz-processing-utils"
version = "0.1.0"
description = ""
authors = ["Anca Chereches <anca.c@transitionzero.org>"]
readme = "README.md"
packages = [
  { include = "tz" }
]

[tool.poetry.dependencies]
python = "^3.11"
pandas = "^2.0.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
